Rollback pyHMMER dependency
pyHMMER 0.8.0 gives the following error with ModelAngelo HMMs. This needs to be investigated:
```
ValueError: Invalid HMM: TMD should be 0 for last node
```